### ISSUE TITLE
Feature Request : declare variables in layer files

### ISSUE THREAD

**Issue by parasbhanot** [robinuniverse/Keebie#17]
Hello everyone , 

i use **xdotool** to simulate key presses and type some command on the terminal but the problem is that json format which is  used in layer files does not support variables .

**Comment by Michael-E-B** [comment]
Would you care to expand on what you mean by variables? Additionally could this be worked around by calling a shell script?

**Comment by daisyUniverse** [comment]
This is an interesting concept but I think that using keebie to call a script is the most simple answer here

**Comment by parasbhanot** [comment]
Following are contents of my default layer. 

```
{
   "KEY_F10": "layer:platformio",
   "KEY_SPACE": "echo 'i am default layer'",
   "KEY_F1": "setxkbmap -option caps:super",
   "KEY_F2": "xdotool key Super_L+p && sleep 0.5s && xdotool type 'htop' && xdotool key Return",
   "KEY_F4": "xdotool key ctrl+shift+F4",
   "KEY_F5": "xdotool key Super_L+p && sleep 0.5s && xdotool type 'yay -Suy' && xdotool key Return",
   "KEY_F6": "xdotool key ctrl+F1",
   "KEY_F7": "xdotool key ctrl+F2",
   "KEY_F8": "xdotool key ctrl+F3",
   "KEY_PAUSE": "xdotool key ctrl+F4",
   "KEY_SCROLLLOCK": "fish /home/parasbhanot/Automation/scripts/reboot.sh"
}
```
i wish i could store the actual commands that i want to execute when press any key on my second keyboard in variable like this  . 

```
PRESS = 'xdotool key'
MOD = 'Super_L'
TYPE ='xdotool type'
SWAP=setxkbmap -option caps:super
DEBUG="echo i am defalut layer"
SWITCH_LAYER="layer:platformio"
SLEEP="sleep 0.5s"
REBOOT="fish /home/parasbhanot/Automation/scripts/reboot.sh"

{
   "KEY_F10": $SWITCH_LAYER,
   "KEY_SPACE": $DEBUG,
   "KEY_F1": "$SWAP",
   "KEY_F2": "$PRESS $MOD && $SLEEP && $TYPE 'htop' && xdotool key Return",
   "KEY_F4": "$PRESS  ctrl+shift+F4",
   "KEY_F5": "$PRESS $MOD && sleep 0.5s && $TYPE 'yay -Suy' && $PRESS Return",
   "KEY_F6": "$PRESS  ctrl+F1",
   "KEY_F7": "$PRESS  ctrl+F2",
   "KEY_F8": "$PRESS  ctrl+F3",
   "KEY_PAUSE": "$PRESS ctrl+F4",
   "KEY_SCROLLLOCK": $REBOOT
}
```

The advantage of this approach is that you do not have to maintain external script file . 

What do you think ?

**Comment by parasbhanot** [comment]
> Would you care to expand on what you mean by variables? Additionally could this be worked around by calling a shell script?

Following are contents of my default layer. 

```
{
   "KEY_F10": "layer:platformio",
   "KEY_SPACE": "echo 'i am default layer'",
   "KEY_F1": "setxkbmap -option caps:super",
   "KEY_F2": "xdotool key Super_L+p && sleep 0.5s && xdotool type 'htop' && xdotool key Return",
   "KEY_F4": "xdotool key ctrl+shift+F4",
   "KEY_F5": "xdotool key Super_L+p && sleep 0.5s && xdotool type 'yay -Suy' && xdotool key Return",
   "KEY_F6": "xdotool key ctrl+F1",
   "KEY_F7": "xdotool key ctrl+F2",
   "KEY_F8": "xdotool key ctrl+F3",
   "KEY_PAUSE": "xdotool key ctrl+F4",
   "KEY_SCROLLLOCK": "fish /home/parasbhanot/Automation/scripts/reboot.sh"
}
```
i wish i could store the actual commands that i want to execute when i press any key on my second keyboard in a variable like this  . 

```
PRESS = 'xdotool key'
MOD = 'Super_L'
TYPE ='xdotool type'
SWAP=setxkbmap -option caps:super
DEBUG="echo i am defalut layer"
SWITCH_LAYER="layer:platformio"
SLEEP="sleep 0.5s"
REBOOT="fish /home/parasbhanot/Automation/scripts/reboot.sh"

{
   "KEY_F10": $SWITCH_LAYER,
   "KEY_SPACE": $DEBUG,
   "KEY_F1": "$SWAP",
   "KEY_F2": "$PRESS $MOD && $SLEEP && $TYPE 'htop' && xdotool key Return",
   "KEY_F4": "$PRESS  ctrl+shift+F4",
   "KEY_F5": "$PRESS $MOD && sleep 0.5s && $TYPE 'yay -Suy' && $PRESS Return",
   "KEY_F6": "$PRESS  ctrl+F1",
   "KEY_F7": "$PRESS  ctrl+F2",
   "KEY_F8": "$PRESS  ctrl+F3",
   "KEY_PAUSE": "$PRESS ctrl+F4",
   "KEY_SCROLLLOCK": $REBOOT
}
```
The advantage of this approach is that you do not have to maintain external script file .

**Comment by daisyUniverse** [comment]
Okay, I think I get it then. in that case I might make keebie read for a specific vars value, ie

```
{
   "VARS":
   [
      "PRESS":"xdotool key",
      "MOD":"Super_L",
      "TYPE :"xdotool type",
      "SWAP":"setxkbmap -option caps:super",
      "DEBUG:"echo i am defalut layer",
      "SWITCH_LAYER":"layer:platformio",
      "SLEEP":"sleep 0.5s",
      "REBOOT":"fish /home/parasbhanot/Automation/scripts/reboot.sh"
   ],
   "KEY_F10": $SWITCH_LAYER,
   "KEY_SPACE": $DEBUG,
   "KEY_F1": "$SWAP",
   "KEY_F2": "$PRESS $MOD && $SLEEP && $TYPE 'htop' && xdotool key Return",
   "KEY_F4": "$PRESS  ctrl+shift+F4",
   "KEY_F5": "$PRESS $MOD && sleep 0.5s && $TYPE 'yay -Suy' && $PRESS Return",
   "KEY_F6": "$PRESS  ctrl+F1",
   "KEY_F7": "$PRESS  ctrl+F2",
   "KEY_F8": "$PRESS  ctrl+F3",
   "KEY_PAUSE": "$PRESS ctrl+F4",
   "KEY_SCROLLLOCK": $REBOOT
}
```
just as an example for how it might be added to the json

**Comment by Michael-E-B** [comment]
Now that it's been explained I like this idea, it shouldn't be terribly difficult to implement. I think I'll start work on this.

**Comment by daisyUniverse** [comment]
Might be a good idea to change the syntax for calling the variables from ${VARNAME} to something else as using that syntax might interfere with native bash variables or vice versa, perhaps prepending each variable with kbv: or something similar would help to stop accidentally replacing words intended to be passed along to the shell

**Comment by Michael-E-B** [comment]
Good point. Might I suggest `%VARNAME`, I can't think of anything it would conflict with.
Edit: Ended up going with `%VARNAME%`. `%` can still be inserted with `\%`, `\` can still be inserted with `\\`.
~~Edit: See issue #23 for why this syntax for escaped `%`s doesn't work.~~

**Comment by daisyUniverse** [comment]
I should note that this could also be accomplished by starting keebie with a bash script and declaring the variables in that, but this solution is cleaner and allows for different sets of variables per layer

**Comment by Michael-E-B** [comment]
Got the main code all done! I've just got to wrap up and push now. I haven't yet added support for editing vars with `--edit` but that sould be pretty easy to do next.

**Comment by daisyUniverse** [comment]
This looks really really good, I quite like that parsing solution, good work as always!

**Comment by daisyUniverse** [comment]
should `/dev/input/event2` be changed back to its default value?

**Comment by Michael-E-B** [comment]
Yes it should, I pushed my personal `settings.json` and `config`. Fixing it now.
Edit: Fixed.

**Comment by Michael-E-B** [comment]
15a165d adds support for `--edit`; my work here is done.

**Comment by parasbhanot** [comment]
Thank you everyone for implementing the feature i really appreciate it.
