### ISSUE TITLE
How to map comma, point or semicolon to KEY_X?

### ISSUE THREAD

**Issue by oOoBlackHoleSunoOo** [robinuniverse/Keebie#19]
Hello, 
so far i can `--add` new `Keys_* ` to the layer-file.json and it works great. 
```
Assign k to [KEY_K]? [Y/n]
```

But how can i add points or comma?
```
Assign . to []? [Y/n] y
Addition cancelled.
<...>
Assign , to []? [Y/n] y
Addition cancelled.
```
Is there a special Format?
I tried  to add `KEY_[.]": "py3:my_script.py"` in the layer file but that does not work.

**Comment by oOoBlackHoleSunoOo** [comment]
Alright found a list input codes seems to work.
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

layer file
```
   "KEY_COMMA": "py3:key_comma.py"
```

**Comment by Michael-E-B** [comment]
I'm not sure what could cause the key to not be detected, I tried to reproduce this and got this:
```
 $ ./keebie.py --add
Welcome to Keebie
Loading settings from settings.json
Enter the command you would like to attribute to a key on your second keyboard 
.
Please press the key combination you would like to assign the command to and hold it for 1 seconds until the next prompt.
Assign . to [KEY_DOT]? [Y/n] n
Addition cancelled.
Would you like to add another Macro? [Y/n] Y
Enter the command you would like to attribute to a key on your second keyboard 
,
Please press the key combination you would like to assign the command to and hold it for 1 seconds until the next prompt.
Assign , to [KEY_COMMA]? [Y/n] n
Addition cancelled.
Would you like to add another Macro? [Y/n] n
```

I was able to get similar behavior if I simply taped the key instead of holding it as instructed:
```
 $ ./keebie.py --add
Welcome to Keebie
Loading settings from settings.json
Enter the command you would like to attribute to a key on your second keyboard 
k
Please press the key combination you would like to assign the command to and hold it for 1 seconds until the next prompt.
Assign k to []? [Y/n] n
Addition cancelled.
Would you like to add another Macro? [Y/n] n
```

But this happens for any key. Whatever the cause I'm glad you found a workaround.

**Comment by oOoBlackHoleSunoOo** [comment]
@Michael-E-B 
I tried it today once again. Now it works.  `Assign . to [KEY_DOT]? [Y/n] ` . ..."shame on me" . :blush: 
Maybe i did not push the key long enough or some magic on my secondary keyboard. 
Great little software, thanks for your effort!
