### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by Michael-E-B** [robinuniverse/Keebie#20]
Firstly it should be noted that I am not a fancy [law talk'n guy](https://www.yout-ube.com/watch?v=DFtbd_pd9rY) (a lawyer).

Assuming [choosealicense.com](https://choosealicense.com/no-permission/) is to be believed in Keebie's current unlicensed state "[...], nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation." which I expect everyone can agree is rubbish. Adding a license would solve this.

This would require consensus among contributors on what license to choose. At present the three contributors are myself, @craftycodie, and @robinuniverse. I would suggest the [MIT Expat License](https://opensource.org/licenses/MIT) or [The Unlicense](https://unlicense.org) (though I understand reservations about public domain, plus it has jurisdiction issues).

Thoughts?

Edit: @parasbhanot is now also a contributor.

**Comment by daisyUniverse** [comment]
Thank you for pointing this out, as it really is kind of an oversight on my part - I usually go with an Apache license or GPL v2, but I would also be alright with putting this on an MIT license, though I will say out of all of them the [Apache License V2 ](https://www.apache.org/licenses/LICENSE-2.0)is my favorite as it is the most hands-off that I know of

**Comment by Michael-E-B** [comment]
I have two issues with the GPL, firstly it's copyleft which personally rubs me the wrong way. Second it's *long*, I don't understand the text of the GPL by reading it because it's like a dense textbook and I end up having to trust that someone else did the understanding for me (I'm the sort of person who likes to know how very step of everything works).

I don't have as much issue with Apache 2.0 (although MIT Expat is more hands-off I think), it is a bit long but I can actually understand it on my own and in exchange it does give nice some nice extras; ~I especially like section 5 as it removes the need for a CLA (at least as far as I can tell)~.

I'm still slightly partial to Expat for it's brevity and The Unlicense for it's freedom, but I'm happy with Apache 2.0.

**Comment by daisyUniverse** [comment]
Yeah GPL is a bit of a mess, I really only like it because other cool software projects that I enjoy also use it, but honestly simplicity and freedom is best. I'll add Apache 2 to it when no one is working on anything. And hey, remember, if we ever need a REALLY simple license, we could always swap over to the [WTFPL](http://www.wtfpl.net/) ;)
