### ISSUE TITLE
Run command without root privilege.

### ISSUE THREAD

**Issue by ghost** [robinuniverse/Keebie#24]
Good evening,
I was wondering if it was possible to access to the second keyboard without root privilege ? I mean, if I do not launch keebie.py as root, it just do not work because it does not have access to the keyboard. Is there something to do I did not ?
Thank you.
![2021-07-11_18-06](https://user-images.githubusercontent.com/66835646/125202182-fe3c4580-e261-11eb-905f-9bb4d701c94f.png)

**Comment by daisyUniverse** [comment]
You need to give your user permission to access the device file, this can be acomplished by doing
`sudo chmod a+rw /dev/input/by-id/[my-device-name]` as specified in the readme

**Comment by ghost** [comment]
Oh yeah indeed, sorry i did not see.
Thank you

**Comment by Michael-E-B** [comment]
You can also add youself to the input group with `usermod -a -G input yourusername`; this doesn't have a good track record, but it has worked for me once (on my current install).

**Comment by daisyUniverse** [comment]
Yeah, the main problem with this method is that not every distro creates an input group, ubuntu and I think fedora do it, but arch linux doesn't, so it's not a super reliable solution

**Comment by Michael-E-B** [comment]
Even on Ubuntu it's not reliable, I've installed Keebie on three (I think) different copies of Ubuntu and it only worked once; same computer, same keyboard, and I think mostly the same version of Ubuntu. But I think it's worth a shot as it's very convenient.
