### ISSUE TITLE
#Dependency   inotify-tools

### ISSUE THREAD

**Issue by Schlump** [robinuniverse/Keebie#30]
While looking for solution to use hotkeys form my new custom keyboard, i stumpled upon this package.

Unfortunately it didn't work out of the box for me (Linux  5.11.0-25-generic #27~20.04.1-Ubuntu )

After looking through the code and trying different options i noticed that when trying to detect any input 

( keebie -d ) the script entered an infinite loop because i was missing a dependency.

` dev = subprocess.check_output("sudo inotifywatch " + path +"/* -t 1 2>&1 | grep " + path + " | awk 'NF{ print $NF }'", shell=True ).decode('utf-8').strip()
`

when trying manually i noticed that i'm missing the package:

> 
> Command 'inotifywatch' not found, but can be installed with:
> 
> sudo apt install inotify-tools

Maybe the dependency should be installed using the makefile, or  documented in the readme.

**Comment by Michael-E-B** [comment]
Installing from the makefile would require a different command per package manager and I can't think of a good way to do that (other than type a command for every single package manager, or telling the user to do it). However you are correct that this is a dependency and should be handled better.

Edit: to be clear installing dependencies from `make install` was what I ment.

**Comment by Michael-E-B** [comment]
Fixed (as best it can be).
