### ISSUE TITLE
New format of device file

### ISSUE THREAD

**Issue by parasbhanot** [robinuniverse/Keebie#31]
Hello everyone , 

i updated the local keebie repository on my machine but then i realized that old config file does not work anymore . Also no sample device file exist in repository and i  do not want to use "_keebie --new_" syntax as it will create the udev rule again .   

What is the format of new device file ?

**Comment by Michael-E-B** [comment]
Here's my device file for `/dev/input/event2`, you can put it in a json file in `~/.config/keebie/devices`.

```
{
   "initial_layer": "default.json",
   "event": "event2",
   "udev_tests": [
      "KERNEL==\"event2\""
   ],
   "udev_rule": "85-keebie-event2.rules"
}
```

Should be simple to adapt it but I would still recommend using `--new`.

**Comment by parasbhanot** [comment]
Thanks

**Comment by Michael-E-B** [comment]
To elaborate `initial_layer` is the name of the layer the device should start on, `event` a path to be prefixed with `"/dev/input/"`, `udev_tests` is a list of tests in the udev rule, not all that important if you are doing things manually, and `udev_rule` is the name of the udev rules file.
