### ISSUE TITLE
Switching layers 

### ISSUE THREAD

**Issue by parasbhanot** [robinuniverse/Keebie#9]
i can neither create nor switch to a layer.

i tried the following to create the layer  :

```
Keebie  🌵 master ✈️  ×1 🍆 ×1 via 🐍 v3.9.1 took 16s ❯  
./keebie.py --add layer:parasbhanot
usage: keebie.py [-h] [--layers] [--device DEVICE] [--add] [--settings]
keebie.py: error: unrecognized arguments: layer:parasbhanot
```

```
Keebie  🌵 master ✈️  ×1 🍆 ×1 via 🐍 v3.9.1 ✖   
./keebie.py --add layer parasbhanot
usage: keebie.py [-h] [--layers] [--device DEVICE] [--add] [--settings]
keebie.py: error: unrecognized arguments: layer parasbhanot
```

Am i missing something here ?

I have also tried to create a layer manually, but I have no idea how to switch to that layer as the documentation is very confusing.

**Comment by Michael-E-B** [comment]
This is an incorrect invocation of Keebie, you should instead run `./keebie.py --add` with no further arguments, this will launch an interactive shell which is where you should enter `layer:parasbhanot` or anything else you wish to bind.

The `layer:` syntax (and all other such syntax i.e. `script:` or `py:` ect) are stored the same as any other command (as a string in a layers JSON file) and are simply detected as you attempt to run them and then interpreted differently.

Your attempted use of `--add` is interesting to me, I might try to implement such syntax in the future (not for a while though, I'm in the middle of making sure I don't lose my home partition to bad sectors).
